# Unsupervised Deep Learning 2024-25 - Introduction to PyTorch

PyTorch is a popular framework for Machine Learning, particularly suitable for **Deep Learning**.
It offers an extensive support for tensor computation with support for GPU acceleration and automatic differentiation.
Nowadays it is the de-facto choice for most researchers due to its ease of use and code readability.

In this tutorial, we are going to cover the basics of PyTorch for Python, including:
- Tensors and images
- Operations
- Automatic differentiation (_autograd_)
- Building and training Neural Networks
  - Transfer learning
  - Training on custom datasets
- Saving and loading models
- Using GPU

we will then transition to Habrok.
Ivaylo will explain how the RUG HPC cluster works and how we can use its functionalities to train our models on the cluster.

## Installation

To install PyTorch, refer to the installation guide on the official website: https://pytorch.org/get-started/locally/.
We strongly suggest you do so in a virtual (conda) environment.

In addition, to reproduce the results of this tutorial, you will need the following libraries:

- NumPy
- Matplotlib

In [ ]:
import torch
import numpy as np

## 1. The Tensor

At the very basics of PyTorch lies the Tensor, an object-oriented implementation of the multidimensional array.
Tensors are the building blocks of PyTorch, and they are used to store data and perform operations on it.

Despite being very similar in functionality to NumPy arrays, PyTorch tensors have some differences.

For instance, a PyTorch tensor will always default to a float32 tensor, regardless of the input data type.

In [5]:
x = torch.Tensor([1,2,3,4,5])
y = np.array([1,2,3,4,5])
print(x)
print("Data type:", x.dtype)
print("------------")
print(y)
print("Data type:", y.dtype)

tensor([1., 2., 3., 4., 5.])
Data type: torch.float32
------------
[1 2 3 4 5]
Data type: int64


Tensors have a shape which we can access with the `shape` attribute or the `size` method.

In [ ]:
x.shape, x.size()

(torch.Size([5]), torch.Size([5]), 1)

We can, additionally, access the number of dimensions with the `dim` attribute.

In [8]:
x.dim()

1

Tensors support an arbitrary number of dimensions:

![](img/tensors.jpg)

In [ ]:
print("2D (matrix)")
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
print("----------------")
print("3D")
x = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)
print(x.shape)
print("----------------")
print("4D")
x = torch.tensor([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(x)
print(x.shape)

2D (matrix)
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
----------------
3D
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
----------------
4D
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
torch.Size([2, 2, 2, 2])


We can add dimensions to a tensor using the `unsqueeze` method.

In [34]:
x = torch.tensor([1,2,3,4])
print(x, "\n", f"Shape: {x.shape}", "\n")

y = x.unsqueeze(dim=0)
print("x.unsqueeze(0) turns x into a row vector")
print(y, "\n", f"Shape: {y.shape}", "\n")


print("Turn x into a column vector:")
# how can we turn x into a column vector?
# your code here

tensor([1, 2, 3, 4]) 
 Shape: torch.Size([4]) 

x.unsqueeze(0) turns x into a row vector
tensor([[1, 2, 3, 4]]) 
 Shape: torch.Size([1, 4]) 

Turn x into a column vector:


We have several ways of constructing tensors, similarly to NumPy

In [17]:
# Create tensor of zeros or ones
print(torch.zeros(2, 3))
print(torch.ones(2, 3))

# Create constant tensor
print(torch.full((2, 3), torch.pi))

# Create sequence tensor
print(torch.arange(0, 12, 2))

# Create sequence tensor with fixed number of elements
print(torch.linspace(0, 10, 6))

# Create tensor as sample from Uniform(0,1)
print(torch.rand(2, 3))

# Create tensor as sample from Normal(0,1)
print(torch.randn(2, 3))

# Create tensor as sample from Normal(2,5)
print(torch.normal(mean=2, std=5, size=(2, 3)))

# Create tensor as sample from Bernoulli(0.5)
print(torch.bernoulli(torch.full((2, 3), 0.5)))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])
tensor([ 0,  2,  4,  6,  8, 10])
tensor([ 0.,  2.,  4.,  6.,  8., 10.])
tensor([[0.3946, 0.7115, 0.1050],
        [0.6489, 0.0580, 0.9146]])
tensor([[ 1.9106,  1.0927, -1.3233],
        [-0.7983, -0.1926,  0.5385]])
tensor([[ 1.7109,  2.5262, -0.2447],
        [10.7194, 14.5181, -3.7983]])
tensor([[0., 1., 1.],
        [1., 1., 0.]])


To reshape tensors, we can use the `reshape` method, specifying the destination dimensions.

Let's take this example form before
```python
print(torch.arange(0, 12, 2))
```

How can we turn this tensor into a 2x3 tensor, like all the other tensor in the cell above?

In [18]:
x = torch.arange(0, 12, 2)
# reshape x into a 2x3 matrix

We can `slice` tensors to extract a subset of the data.

Slicing works similarly as in NumPy

In [24]:
x = torch.arange(0, 24).reshape(4, 3, 2)

print(f"Original x (shape {x.shape}):")
print(x, "\n")

print(f"Get only first matrix (x[0]):")
print(x[0], "\n")

print(f"Get only first row of first matrix (x[0,0]):")
print(x[0,0], "\n")

print(f"Get only first element of first row of first matrix (x[0,0,0]):")
print(x[0,0,0], "\n")

print(f"Get first two rows of second and third matirx of x (x[1:3,:2]):")
print(x[1:3,:2], "\n")

print(f"Get first and third rows of second and third matirx of x (x[1:3,(0,2)]):")
print(x[1:3,(0,2)], "\n")

Original x (shape torch.Size([4, 3, 2])):
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]) 

Get only first matrix (x[0]):
tensor([[0, 1],
        [2, 3],
        [4, 5]]) 

Get only first row of first matrix (x[0,0]):
tensor([0, 1]) 

Get only first element of first row of first matrix (x[0,0,0]):
tensor(0) 

Get first two rows of second and third matirx of x (x[1:3,:2]):
tensor([[[ 6,  7],
         [ 8,  9]],

        [[12, 13],
         [14, 15]]]) 

Get first and third rows of second and third matirx of x (x[1:3,(0,2)]):
tensor([[[ 6,  7],
         [10, 11]],

        [[12, 13],
         [16, 17]]]) 



Additionally, we can use the `:` symbol in a given dimension to request all of the elements from a particular dimension.

You can try solving this without using for loops:

* Extract the first row of each matrix of `x`
* Extract the first column of each matrix of `x`

In [ ]:
# your code here

Notice that this

`Get only first element of first row of first matrix (x[0,0,0])`

returns this

`tensor(0)`.

This is different from the NumPy behavior, where it would return a scalar.
We can extract the scalar value of "singleton tensors" using the `item` method.


In [36]:
x = torch.arange(0, 12, 2).reshape(2, 3)
val = x[1, 2]
print(val, ";" ,val.item())

tensor(10) ; 10


### Tensor operations

Tensors support a wide range of linear algebra operations.

The main thing we need to be careful is that the basic arithmetic operations (+, -, *, /, //, %) are **element-wise**.

The multiplication `*` does not correspond to the scalar product, but to the Hadamard (element-wise) product.

Be also careful to the dimensions.

In [38]:
x = torch.arange(0, 12, 2).reshape(2, 3)
y = torch.arange(1, 7).reshape(2, 3)

print(x)
print(y)

x * y

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])
tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[ 0,  4, 12],
        [24, 40, 60]])

In [40]:
x = torch.arange(0, 12, 2).reshape(2, 3)
y = torch.arange(1, 7).reshape(3, 2)

x * y # this is not matrix multiplication!

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Matrix multiplication can be performed using `@` or `matmul`:

In [ ]:
print(x @ y)

print(x.matmul(y))

print(x.mm(y))

print(torch.matmul(x, y))


tensor([[ 26,  32],
        [ 80, 104]])
tensor([[ 26,  32],
        [ 80, 104]])
tensor([[ 26,  32],
        [ 80, 104]])
tensor([[ 26,  32],
        [ 80, 104]])
tensor([[ 0, 12],
        [ 6, 32],
        [20, 60]])


Be careful also at vector multiplication:

In [45]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,5,6])

print(x * y) # not a dot product
print(torch.dot(x, y)) # dot product
print(x @ y) # dot product

tensor([ 4., 10., 18.])
tensor(32.)
tensor(32.)


#### Dimensional operations

We can perform operations along a given dimension using the `dim` argument.

Let's suppose we want to get the sum of all the rows of a matrix.

We can use the `sum` method with the `dim` argument set to 1.

In [48]:
x = torch.arange(0, 12, 2).reshape(2, 3)
print(x)
print("----------------")
print("Sum of rows of x")

print(x.sum(dim=1))

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])
----------------
Sum of rows of x
tensor([ 6, 24])


`x.sum(dim=1)` means: we iterate over the dimension 1 (rows) and sum all the elements for each iteration.

The concept of dimensional operations can be applied to very common reduction operations, such as `mean`, `std`, `max`, `min`, and even the norm.

In [53]:
x = torch.arange(0, 12, 2).reshape(2, 3).float()

print(x)
print("----------------")

print("Norm of x")
print(x.norm()) # defaults to frobenius norm

print("----------------")
print("Norm of x with p=1")
print(x.norm(p=1)) # Manhattan distance

print("----------------")
print("Matrix L1 norm")
print(torch.linalg.norm(x, ord=1))

print("----------------")
print("L2 norm of every column")
print(x.norm(dim=0))
print("L2 norm of every row")
print(x.norm(dim=1))



tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
----------------
Norm of x
tensor(14.8324)
----------------
Norm of x with p=1
tensor(30.)
----------------
Matrix L1 norm
tensor(14.)
----------------
L2 norm of every column
tensor([ 6.0000,  8.2462, 10.7703])
L2 norm of every row
tensor([ 4.4721, 14.1421])


**Exercise**

Consider the tensor `x` defined as `x = torch.arange(0, 24).reshape(3, 2, 4)`.
This tensor can be used to represent an RGB image of dimension 2x4 pixels.

![](img/rgb_image.png)

Compute the per-channel mean of the image.

In [ ]:
# your code here

*Note:* 

While images are normally stored as 3D tensors `(height, width, channels)`, PyTorch uses a different convention `(channels, height, width)`.

You can transition between the two conventions using the `permute` method.

In [1]:
img_torch = torch.arange(0, 24).reshape(3, 2, 4)

img_classic = img_torch.permute(1, 2, 0) # shift first dimension to last

img_torch = # your code here - recover img_torch from img_classic

SyntaxError: invalid syntax (1458234257.py, line 5)